### ISSUE TITLE
Provide binaries for linux64 and MacOS/darwin in Releases?

### ISSUE THREAD

**Issue by tseemann** [natir/fpa#11]
I believe Go can create small static binaries
Would be great to have these as part of the releases

**Comment by natir** [comment]
fpa isn't a Go application it's Rust application.

I can add linux static binaries.

I refuse to spent time, in cross-compilation to generate MacOS static binaries

**Comment by tseemann** [comment]
My apologies for mixing Rust and Go up in my mind (I always get thrown by `cargo`!)
What I ask for is trivial in Go, but yes, less so for Rust.

I see that the bioconda authors failed to build it on MacOS too:
```
  skip: True # [osx]
```
This suggests it is difficult to build from source on MacOS ?

But i guess if you feel it won't be used on MacOS much enough to worry about lost citations that's a fair decision.

(My original goal was to spend my time packageing your tool for Homebrew and Linuxbrew.)

**Comment by natir** [comment]
Sorry, I just reread myself and realized that my answer was rude.

> `skip: True # [osx]`

Strange isn't set in yacrd bioconda package maybe I can try to remove it. 

> This suggests it is difficult to build from source on MacOS ?

I think not. I don't have MacOS, cross compile rust from Linux to MacOS (it's probably easier than C/C++) but requeried some instalation and setup and I have no time for this thing actualy, sorry.

 > (My original goal was to spend my time packageing your tool for Homebrew and Linuxbrew.)

For this I think you just need install [rust toolchain](https://rustup.rs/),  download source and run:
```
cargo build --release
```

Binary file `target/release/fpa` is dynamic link, but only to some basic system libraries so I'm not sure you need static binary file.

If you need more help didn't hessistate to ask.

I'm again sorry for the tone of my first answer.

**Comment by natir** [comment]
Hi @tseemann,

I remove the skip of osx in bioconda package and all the [test was passed] so I think there is no trouble to build fpa in MacOS.

bioconda/bioconda-recipes#18159

Pierr
