### ISSUE TITLE
How to keep overlaps

### ISSUE THREAD

**Issue by ardy20** [natir/fpa#13]
Dear Authors

I already created a .paf file from minimap2. Now, I need to filter it for self-mapped and then choose the best overlaps for assembly.

Could you please give an example how to drop self mapped and also use gfa from a paf file already created in minimap2?

For example:  

Is this correct?

fpa drop -m -n my.reads.fasta | gzip -1 > overlap.noself.paf.gz or should be

fpa drop -m overlaps.paf.gz -n WRA25%60Kb.fasta | gzip -1 > overlap.noself.paf.gz

How gfa command can be used on a .paf input file?

**Comment by natir** [comment]
Hi,

To filter self overlap you can run:
```
fpa -i overlap.paf.gz -o overlap.noself.paf.gz drop -m
```
fpa detect automatically input compression format and reuse it for output to overide it use option -z.

If you want produce a gfa from your paf file you can run:
```
fpa -i overlap.paf -o /dev/null gfa -o overlap.gfa
```
if you want keep containment and internal match overlap in your gfa you can add `-c` and `-i` after `gfa`

I didn't understand this two question:

> use gfa from a paf file already created in minimap2?
> How gfa command can be used on a .paf input file?

`drop`,  `gfa`, `index`, `keep`, `rename` are sub-command each of them have their own help message don't hesitate to use it.

**Comment by natir** [comment]
@ardy20 You can close this issue if your trouble is solve.
