### ISSUE TITLE
The meanings of internal match and containment

### ISSUE THREAD

**Issue by JieZhouFighting** [natir/fpa#15]
Dear Authors,

I don't understand the meanings of internal match and containment clearly, so I want to know their meanings and what characteristics they have in the alignment file.

**Comment by natir** [comment]
Hi,

I think the best definition could be find in [Minimap and Miniasm](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4937194/) publication check Figure 1 and Algorithm 5. We just apply this algorithm.

If I solve your trouble please close this issue. If you have any other question, don't hesitate to create another issue.
