### ISSUE TITLE
error building v0.4

### ISSUE THREAD

**Issue by lfaino** [natir/fpa#2]
Dear,
i get this error when i compile from source the v0.4 version using the command:

git checkout v0.4
cargo build

the error:

   Compiling fpa_lr v0.4.0 (/home/lfaino/bin/fpa)
error[E0106]: missing lifetime specifier
  --> src/modifier/indexing.rs:40:11
   |
40 | impl From<&str> for IndexType {
   |           ^ expected lifetime parameter

error: aborting due to previous error

For more information about this error, try `rustc --explain E0106`.
error: Could not compile `fpa_lr`.

To learn more, run the command again with --verbose.

**Comment by natir** [comment]
Hello and thank you for reporting this issue.

What is your version of rustc?

I forgot to indicate in the readme that you need rustc version 1.32, I fix it in c19dea3e0522f603e1db7e62bc748d08d51ca4f9.

Sorry again for the inconvenience.

**Comment by lfaino** [comment]
thanks is worked
