### ISSUE TITLE
Options(s) for dropping self match?

### ISSUE THREAD

**Issue by ilnamkang** [natir/fpa#9]
Hi,

I'm having difficulty in finding command line options(s) for dropping self match.

I've tried "-s" following several commands presented in Readme, but it seems to be for length filtering.

Are there any options for dropping self match?

Thanks.

Ilnam

**Comment by natir** [comment]
Hi,

Thank you for opening this issue.

Sorry I forgot to change these commands in the readme after the last update.

The option to filter self match is now `-m` or `--same-name`.

Again, I'm sorry for this mistake.
